### ISSUE TITLE
Tester 시나리오

### ISSUE THREAD

**Issue by accidentlywoo** [JavaConsoleProgram/GitStart#10]

**Comment by captic94** [comment]
Server

○ 2001 신입생의 예상 출력물
 1. 로그인 전 메인화면
 - 학번찾기
  -> 성공  "조회된 학생번호는 2020999999 입니다"
      실패  "조회에 실패하였습니다."			-> 학번찾기 반복(0입력시 까지)

 - 비밀번호 수정
  -> 성공 "비밀번호가 수정되었습니다."		-> 후 자동으로 로그인 전 메인화면으로 이동	-> test
      실패 "비밀번호 수정에 실패하였습니다."		-> 비밀번호 수정 반복(0입력시 까지)

 - 로그인
 -> 성공 						-> 로그인 후 화면으로 이동
     실패 "로그인에 실패하셨습니다."			-> 후 자동으로 로그인 전 메인화면으로 이동


 2. 로그인 후 화면
 - 내 정보 조회
  -> 학번		: 2020999999
      학과이름	: architecture
      이메일	: test@test.tst

   -- 내 정보 수정하기
    1	이메일  	>  성공  "[이메일]로 변경되었습니다."		-> testtest@test.tt
		    실패 "이메일 변경에 실패하였습니다."
		  (중복시) "이미 사용중인 이메일입니다."
    2	비밀번호	> 성공  "비밀번호가 변경되었습니다."		-> 9test
		   실패  "비밀번호 변경에 실패하였습니다."
    0	뒤로가기 > 로그인 후 화면으로 이동

 - 수강신청하기
 -> 수강신청 화면으로 이동

 - 이번 학기 내 시간표 보기
  -> "수강신청한 과목이 없습니다."

 - 성적 조회
  -> "조회된 학번의 정보가 없습니다"

 - 로그아웃
  -> "로그아웃 하시겠습니까? (맞으면 0을 입력해주세요)"
     0 :  로그인 전 메인화면으로 이동
    그외: 로그인 후 화면으로 이동


 3. 수강신청
 - 1. 수강신청목록[수강신청하기]
   전공/교양    교과목번호         교과목명    학점       강의시간    수강정원 수강신청인원 교수명   강의실정보  재수강해당
     전공      200150019502  건축구조의이해   3    TUE11:0014:00     15            0	   권기호  공학관 203호      N
     전공      200150029503    건축환경물리    3    MON09:0012:00   15            0	   김성배	 공학관 103호      N
						...
------------------------------------------------------------------------------------------------------------------------------------------------
   [내 수강신청 목록]
   전공/교양    교과목번호         교과목명    학점       강의시간    수강정원 수강신청인원 교수명   강의실정보  재수강해당

--이수학점(전공) : 0(0)------------------------------------------------------------------------------------------------------------------------

 -> 200161019601
  수강신청 성공 시

   전공/교양    교과목번호         교과목명    학점       강의시간    수강정원 수강신청인원 교수명   강의실정보  재수강해당
     전공      200150019502  건축구조의이해   3    TUE11:0014:00     15            0	   권기호  공학관 203호      N
     전공      200150029503    건축환경물리    3    MON09:0012:00   15            0	   김성배	 공학관 103호      N
						...
     교양      200161019601 소설로읽는북한...  3	    MON09:0012:00	  10             1	   장경남  교육관 101호      N
------------------------------------------------------------------------------------------------------------------------------------------------
   [내 수강신청 목록]
   전공/교양    교과목번호         교과목명    학점       강의시간    수강정원 수강신청인원 교수명   강의실정보  재수강해당
     교양      200161019601 소설로읽는북한...  3	    MON09:0012:00	  10             1	   장경남  교육관 101호      N
--이수학점(전공) : 3(0)------------------------------------------------------------------------------------------------------------------------


===> 0번 입력시 까지 반복

   수강신청 실패 시
   - 잘못된 교과목 번호 입력시 -> "신청 할 수 있는 과목이 없습니다."

 - 수강 신청한 목록 보기
[내 수강신청 목록]
월 : 1교시(200161019601, 소설로읽는북한문학)
--이수학점(전공) : 3(0)------------------------------------------------------------------------------------------------------------------------

 -> 200161019601 입력시
  수강취소 성공 시		-> 0번 누를시 까지 반복

	  실패 시	-- 수강신청 과목이 없거나 잘못 입력할 시 >> "잘못된 값을 입력 하였습니다."
