### ISSUE TITLE
[f702149073b2801964d7824acd8caa09ec62fe64] Multi Thread 환경에서 이런 싱글톤으로 안전한가?

### ISSUE THREAD

**Issue by accidentlywoo** [JavaConsoleProgram/GitStart#7]
기본 싱글톤 패턴으로 Service / DAO 를 구현하고 뒹굴거리다가, Multi Thread 환경에서 저 싱글톤만으로 괜찮은가?를 고민하다가 공부하고 코드수정을 진행할 예정입니다.

```
public class ClassInfoService {
	private static final ClassInfoService classInfoService =null;
        private ClassInfoService() {}
	public static ClassInfoService getInstance(){
		if(classInfoService == null){
		    classInfoService = new ClassInfoService();
		}
		return classInfoService;
	}
}
```
위같은 기본 싱글톤 패턴은 Multi Thread환경에서 두개이상의 Thread가 인스턴스를 획득하기 위해 getInstance()메서드에 진입하여 경합을 벌이는 과정에서 어떤 문제가 발생할까요?
서로 다른 두 개의 인스턴스가 만들어지는 형태가 발생할 수 있습니다. 

제가 올린 소스코드는 처음부터 인스턴스를 생성해버리고 final키워드를 붙여 명시적으로 싱글톤임을 확정지어줬습니다.
이 소스의 단점은, 미리 인스턴스를 만들어버려서, 불필요한 시스템 리소스를 낭비할 가능성이 있다는 것입니다. 
```
public class ClassInfoService {
        private static final ClassInfoService classInfoService = new ClassInfoService();
        private ClassInfoService() {}
	public static ClassInfoService getInstance(){
		return classInfoService;
	}
}
```

다른 방법 1. 메소드를 동기화시키자!
```
public class ClassInfoService {
	private static final ClassInfoService classInfoService =null;
        private ClassInfoService() {}
	public synchronized static ClassInfoService getInstance(){
		if(classInfoService == null){
		    classInfoService = new ClassInfoService();
		}
		return classInfoService;
	}
}
```
getInstance() 메소드에 synchronized 키워드를 붙여 Thread Safe한 메소드를 선언해주었습니다. 하지만 이방식은 일반적으로 성능을 100배 정도 저하시키다고 합니다. (Synchronized는 정말 중요한 사항 예를들어 Transactional 구현할때만 사용해야합니다.)

다른 방법 2. LazyHolder 기법
```
public class ClassInfoService {
       private ClassInfoService() {}
	public static ClassInfoService getInstance(){
		return LazyHolder.INSTANCE;
	}
	private static class LazyHolder{
		private static final ClassInfoService INSTANCE = new ClassInfoService();
	}
}
```
LazyHolder 기법으로 synchronized도 필요없고, 자바 버전도 상관없는 방법입니다. getInstance() 메소드에서 LaztHolder.INSTANCE를 참조하는 순간 Class가 로딩되며 초기화가 진행됩니다. 
Class 를 로딩하고 초기화하는 시점은 thread-safe를 보장하기 때문에 volatile이나 synchronized같은 키워드가 없어도 된다.

Service / DAO를 LazyHolder 방식으로 소스를 Refactoring 할 예유!

**Comment by captic94** [comment]
예유! 죠습니다 좋은거 잘 알려주신거 같아여
