### ISSUE TITLE
테스트 시나리오가 필요합니다! 06/29(월요일) 

### ISSUE THREAD

**Issue by accidentlywoo** [JavaConsoleProgram/GitStart#8]
테스트 시나리오 작성 및 테스트 코드 작성이 필요합니당. 
월요일 2 P.M. 중간점검 테스트 시나리오 : Server 파트 : 팀장님이 테스트 시나리오 작성과 테스트 코드작성을 추가해주세요.

* 테스트 시나리오 짜는 방법 ex) Server 데이터 출력 파트 / Client Flow 파트*

Server
- 2001 신입생의 예상 출력물 : 1. 로그인 전 ~ 2. 로그인 후~ 3. 수강신청~
- 1901 History가 있는 학생 : 1. 로그인 전 ~ 2. 로그인 후~ 3. 수강신청~

Client 파트
- Notion 화면설계와 같은 흐름인지 실행 테스트 : 전체 단계 별로

**Comment by captic94** [comment]
아 여기였군요 확인했습니다
